### PR TITLE
Reworking the original site

### PR DESCRIPTION
**Pull request by Mesoptier**
New design and some new features

### CODE REVIEW

**Comment by callumacrae** [comment]
Thanks! What syntax do I want for matching tests?

**Comment by LarryBattle** [comment]
http://mesoptier.github.com/regex-tuesday/challenge1.html 
Wow. That looks a lot better. 

It would be nice if the test could emphasis that you're using the `str.replace( RE_box1, replaceWith_box2 )`;

**Comment by callumacrae** [comment]
Merged - thanks @Mesoptier!

**Comment by callumacrae** [comment]
@Mesoptier I'm bringing this project back and have just ported this design into a React app :open_mouth:

**Comment by Mesoptier** [comment]
Neat :D

**Pull request merged**
